import { Injectable } from '@nestjs/common'
import { VocabService } from './vocab.service'
import { VocabWordDocument } from './vocab.schema'

export interface QuestionOption {
  id: string
  text: string
  isCorrect: boolean
}

export interface QuestionPayload {
  wordId: string
  type: 'choice' | 'quiz' | 'spelling' | 'sentence'
  questionText: string
  options?: QuestionOption[]
  answer?: string
}

@Injectable()
export class QuestionGeneratorService {
  constructor(
    private vocabService: VocabService
  ) {}

  /**
   * 题目生成 - 选择题
   * @param userLevel 用户学段 (规范化后: 'Primary' | 'Middle' | 'High' | 'CET4' | 'CET6' | 'University' | 'Professional')
   *   - 优先用用户 profile.educationLevel (学习侧按学段展示分级释义)
   *   - 兜底: word.levels?.[0] (旧行为, controller 传入 undefined 时)
   * 该参数同时影响: 干扰项池 (getRandomDistractors) + 释义 key (getGradeDefinition)
   *
   * isDirtyGradeDefinition / getGradeDefinition 已搬到 vocab.service (2026-06-09 B 任务),
   * C-Phase2 admin 词库体检也用 vocabService.isDirtyGradeDefinition 标脏
   */
  async generateChoiceQuestion(
    word: VocabWordDocument,
    mode: 'en-zh' | 'zh-en',
    userLevel?: string
  ): Promise<QuestionPayload> {
    const level = userLevel || word.levels?.[0] || 'junior'
    const distractors = await this.vocabService.getRandomDistractors(3, String(word._id), level)

    let questionText: string
    let correctText: string
    let distractorTextFn: (w: any) => string

    if (mode === 'en-zh') {
      questionText = word.headword
      // 使用分级释义而非原始复杂释义
      correctText = this.vocabService.getGradeDefinition(word, level)
      distractorTextFn = (w) => this.vocabService.getGradeDefinition(w, level)
    } else {
      questionText = this.vocabService.getGradeDefinition(word, level)
      correctText = word.headword
      distractorTextFn = (w) => w.headword
    }

    const options: QuestionOption[] = [
      { id: String(word._id), text: correctText, isCorrect: true },
      ...distractors.map(d => ({
        id: String(d._id),
        text: distractorTextFn(d),
        isCorrect: false
      }))
    ]

    // Shuffle options
    options.sort(() => Math.random() - 0.5)

    return {
      wordId: String(word._id),
      type: 'choice',
      questionText,
      options
    }
  }

  async generateQuizQuestion(word: VocabWordDocument): Promise<QuestionPayload> {
    // Context-based question using example sentence if available
    // We also need to check if the example is a dummy one generated by the seed script (e.g., "Example for apple")
    const isDummyExample = word.exampleEn?.startsWith('Example for ') && word.exampleEn?.includes(word.headword);

    if (word.exampleEn && !isDummyExample) {
       // Hide the word in the example sentence
       // Simple regex replacement of the headword (case insensitive)
       const escaped = word.headword.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
       const regex = new RegExp(`\\b${escaped}\\b`, 'gi')

       // If the word is not found in example (sometimes happens due to lemma/form diff), fallback
       if (!regex.test(word.exampleEn)) {
          return this.generateChoiceQuestion(word, 'zh-en')
       }

       const questionText = word.exampleEn.replace(regex, '______')

       // Distractors: other words from same level
       const distractors = await this.vocabService.getRandomDistractors(3, String(word._id), word.levels?.[0])

       const options: QuestionOption[] = [
          { id: String(word._id), text: word.headword, isCorrect: true },
          ...distractors.map(d => ({
             id: String(d._id),
             text: d.headword,
             isCorrect: false
          }))
       ]
       options.sort(() => Math.random() - 0.5)

       return {
          wordId: String(word._id),
          type: 'quiz',
          questionText: `${questionText}`,
          options
       }
    }

    // Fallback to choice if no example
    return this.generateChoiceQuestion(word, 'zh-en')
  }

  /**
   * Stage 3 造句题:用户用目标词造一个英文句子
   * - 不给选项,纯文本输入
   * - 后端用 DeepSeek.evaluateSentence 判分
   * - 答对算掌握,触发 WordMastery + +10 金币(沿用 scheduler 逻辑)
   * - 答错 SRS 降 EF/reps(不降 stage,因为是已掌握)
   */
  async generateSentenceQuestion(word: VocabWordDocument): Promise<QuestionPayload> {
    return {
      wordId: String(word._id),
      type: 'sentence',
      // 简短中文指令,SentenceQuestion 组件会用 question.word.definition 做更细展示
      questionText: `请用 "${word.headword}" 造一个英文句子`
    }
  }
}
